
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAJEEV
 */
public class Created extends javax.swing.JFrame {

    /**
     * Creates new form Created
     */
    public Created() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        profession = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        summary = new javax.swing.JLabel();
        SkillLabel = new javax.swing.JLabel();
        SKILL2 = new javax.swing.JLabel();
        SKILL1 = new javax.swing.JLabel();
        SKILL3 = new javax.swing.JLabel();
        EducationLabel = new javax.swing.JLabel();
        HighSchoolName = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        SeniorSecSchool = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        clg1name = new javax.swing.JLabel();
        degree1 = new javax.swing.JLabel();
        clg2name = new javax.swing.JLabel();
        degree2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(242, 243, 234));
        jLayeredPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 48)); // NOI18N
        jLabel1.setText("name");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Create Resume");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        profession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profession.setText("profession");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("email");

        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setText("phone no.");

        About.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        About.setText("About");

        summary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        summary.setText("summary");

        SkillLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SkillLabel.setText("Skills");

        SKILL2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SKILL2.setText("skill2");

        SKILL1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SKILL1.setText("skill1");

        SKILL3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SKILL3.setText("skill3");

        EducationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EducationLabel.setText("Education");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(profession, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(phone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(About, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(summary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SkillLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SKILL2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SKILL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SKILL3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(EducationLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SkillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(profession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))))
                            .addComponent(SKILL1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SKILL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SKILL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EducationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profession)
                    .addComponent(email))
                .addGap(18, 18, 18)
                .addComponent(phone)
                .addGap(38, 38, 38)
                .addComponent(About)
                .addGap(18, 18, 18)
                .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(SkillLabel)
                .addGap(26, 26, 26)
                .addComponent(SKILL1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SKILL2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SKILL3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(EducationLabel))
        );

        HighSchoolName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HighSchoolName.setText("highSchool");

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl1.setText("Class 10 ");

        SeniorSecSchool.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SeniorSecSchool.setText("SeniorSchool");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl2.setText("Class 12");

        clg1name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clg1name.setText("clg1 name");

        degree1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        degree1.setText("degree1");

        clg2name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clg2name.setText("clg2 name");

        degree2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        degree2.setText("degree2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HighSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeniorSecSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clg1name, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clg2name, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree2, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addGap(18, 18, 18)
                .addComponent(HighSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeniorSecSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clg1name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degree1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clg2name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degree2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String first_name = jTextField1.getText();
        String name = "";
        String email_id;
        String Phone_no;
        String Profession;
       
        try{
    Class.forName("com.mysql.jdbc.Driver");  
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/resume_maker?characterEncoding=UTF-8","root","");
     
    if (con != null) {
                System.out.println("Connection to the database has been established.");
                
                // You can now perform database operations here.
                Statement stmt1 = con.createStatement(); 
               String query1 = "SELECT last_name, email_id, Phone_no, Profession FROM user_details WHERE first_name = \"" + first_name + "\";";
                Statement stmt2 = con.createStatement(); 
               String query2 = "SELECT high_school_name, senior_secondary_school_name, degree1_name, college1_name, degree2_name, college2_name FROM education WHERE first_name = \"" + first_name + "\";";
               Statement stmt3 = con.createStatement(); 
               String query3 = "SELECT summary FROM summary WHERE first_name = \"" + first_name + "\";";
               Statement stmt4 = con.createStatement(); 
               String query4 = "SELECT skill1, skill2, skill3 FROM skills WHERE first_name = \"" + first_name + "\";";
               //execute the query 
               java.sql.ResultSet resultSet1 =  stmt1.executeQuery(query1);
                java.sql.ResultSet resultSet2 =  stmt2.executeQuery(query2);
                java.sql.ResultSet resultSet3 =  stmt3.executeQuery(query3);
                java.sql.ResultSet resultSet4 =  stmt4.executeQuery(query4);
               if (resultSet1.next()&& resultSet2.next() && resultSet3.next() && resultSet4.next()) {
    // There is data in the result set; you can safely retrieve it
     name = first_name +" "+ resultSet1.getString("last_name");
                     email_id = resultSet1.getString("email_id");
                    Phone_no = resultSet1.getString("Phone_no");
                     Profession = resultSet1.getString("Profession");
                    jLabel1.setText(name);
                    email.setText(email_id);
                    phone.setText(Phone_no);
                    profession.setText(Profession);
                   String Summary = resultSet3.getString("summary");
                    summary.setText(Summary);
                    String skill1 = resultSet4.getString("skill1");
                    SKILL1.setText(skill1);
                     String skill2 = resultSet4.getString("skill2");
                    SKILL2.setText(skill2);
                     String skill3 = resultSet4.getString("skill3");
                    SKILL3.setText(skill3);
                     String high = resultSet2.getString("high_school_name");
                    HighSchoolName.setText(high);
                     String senior = resultSet2.getString("senior_secondary_school_name");
                    SeniorSecSchool.setText(senior);
                    String Deg1 = resultSet2.getString("degree1_name");
                    degree1.setText(Deg1);
                     String Deg2 = resultSet2.getString("degree2_name");
                    degree2.setText(Deg2);
                    clg1name.setText(resultSet2.getString("college1_name"));
                    clg2name.setText(resultSet2.getString("college2_name"));
    // Continue processing data here
} else {
    // The result set is empty; handle this case as needed
    System.out.println("Result set is empty.");
}
               
               
                
         //close the connection
         resultSet1.close();
         resultSet2.close();
         resultSet3.close();
         resultSet4.close();
            stmt1.close();
            stmt2.close();
            stmt3.close();
            stmt4.close();
            con.close();
          
    } else {
                System.out.println("Failed to establish a connection to the database.");
            }
    }catch(Exception e){
    System.out.println(e);
    }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Created.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Created.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Created.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Created.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Created().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel EducationLabel;
    private javax.swing.JLabel HighSchoolName;
    private javax.swing.JLabel SKILL1;
    private javax.swing.JLabel SKILL2;
    private javax.swing.JLabel SKILL3;
    private javax.swing.JLabel SeniorSecSchool;
    private javax.swing.JLabel SkillLabel;
    private javax.swing.JLabel clg1name;
    private javax.swing.JLabel clg2name;
    private javax.swing.JLabel degree1;
    private javax.swing.JLabel degree2;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel profession;
    private javax.swing.JLabel summary;
    // End of variables declaration//GEN-END:variables
}
